name: Analyze code and Unit test

on:
  push:
    branches: [main, stable]
  pull_request:
    branches: [main, stable]

jobs:
  flutter_test:
    name: Analyze code and Unit test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: "stable"
      - run: flutter doctor

      - name: "Check fmt"
        run: flutter analyze --fatal-warnings

      - name: "Analyze Code"
        run: flutter analyze --fatal-warnings

      - name: "Run unit tests"
        run: flutter test
