name: Build Android

on:
  push:
    branches: [main, stable]
  pull_request:
    branches: [main, stable]

jobs:
  build_android:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: "stable"
      - run: flutter doctor

      - name: "Build apk"
        run: flutter build apk

      - name: "Build appbundle"
        run: flutter build appbundle
