name: Build IOS

on:
  push:
    branches: [main, stable]
  pull_request:
    branches: [main, stable]

jobs:
  build_ios:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: "stable"
          architecture: x64
      - run: flutter doctor

      - name: "Build IOS"
        run: flutter build ios --release --no-codesign
