name: CI IOS

on:
  push:
    branches: [main, stable]
  pull_request:
    branches: [main, stable]

jobs:
  integration_test_ios:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: stable
      - run: flutter doctor -v

      - uses: futureware-tech/simulator-action@v2
        with:
          model: "iPhone 14"
          os_version: "16.2"

      - name: Integration Test
        run: flutter drive --target=test_driver/app.dart --dart-define=screenshot=true

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: my-artifact
          path: ./screenshots/*
